services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: laravel-app
        container_name: laravel-app
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        ports:
            - "9000:9000"
        networks:
            - laravel_network
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - app
        networks:
            - laravel_network
    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: labnissi
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: laravel
            MYSQL_PASSWORD: 123456
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network
networks:
  laravel_network:
    driver: bridge
volumes:
    dbdata:
